dir .
dir ../../gcc-4.4.7/gcc
dir ../../gcc-4.4.7/gcc/ada
dir ../../gcc-4.4.7/gcc/cp
dir ../../gcc-4.4.7/gcc/fortran
dir ../../gcc-4.4.7/gcc/java
dir ../../gcc-4.4.7/gcc/objc
dir ../../gcc-4.4.7/gcc/objcp
source ../../gcc-4.4.7/gcc/gdbinit.in
