
all:

clean:

romfs:
	$(ROMFSINST) /etc_ro/koolproxy.tgz
	$(ROMFSINST) /etc_ro/ad_config_script.sh
	$(ROMFSINST) /etc_ro/koolproxy.sh
	$(ROMFSINST) /etc_ro/koolproxy_rules_list.sh
	$(ROMFSINST) /etc_ro/koolproxy_rules_script.sh